'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3625
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("8e68db06-a418-45fd-9909-9c20e42fb934")> 

'Original file name: Statistics.ObjectLayer.vb
'Generation date: 2012-03-12 08:31:18
Namespace EDM
    '''<summary>
    '''There are no comments for StatisticsContext in the schema.
    '''</summary>
    Partial Public Class StatisticsContext
        Inherits Global.System.Data.Objects.ObjectContext
        '''<summary>
        '''Initializes a new StatisticsContext object using the connection string found in the 'StatisticsContext' section of the application configuration file.
        '''</summary>
        Public Sub New()
            MyBase.New("name=StatisticsContext", "StatisticsContext")
            Me.OnContextCreated
        End Sub
        '''<summary>
        '''Initialize a new StatisticsContext object.
        '''</summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "StatisticsContext")
            Me.OnContextCreated
        End Sub
        '''<summary>
        '''Initialize a new StatisticsContext object.
        '''</summary>
        Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
            MyBase.New(connection, "StatisticsContext")
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        '''<summary>
        '''There are no comments for dtproperties in the schema.
        '''</summary>
        Public ReadOnly Property dtproperties() As Global.System.Data.Objects.ObjectQuery(Of dtproperties)
            Get
                If (Me._dtproperties Is Nothing) Then
                    Me._dtproperties = MyBase.CreateQuery(Of dtproperties)("[dtproperties]")
                End If
                Return Me._dtproperties
            End Get
        End Property
        Private _dtproperties As Global.System.Data.Objects.ObjectQuery(Of dtproperties)
        '''<summary>
        '''There are no comments for tptest in the schema.
        '''</summary>
        Public ReadOnly Property tptest() As Global.System.Data.Objects.ObjectQuery(Of tptest)
            Get
                If (Me._tptest Is Nothing) Then
                    Me._tptest = MyBase.CreateQuery(Of tptest)("[tptest]")
                End If
                Return Me._tptest
            End Get
        End Property
        Private _tptest As Global.System.Data.Objects.ObjectQuery(Of tptest)
        '''<summary>
        '''There are no comments for dtproperties in the schema.
        '''</summary>
        Public Sub AddTodtproperties(ByVal dtproperties As dtproperties)
            MyBase.AddObject("dtproperties", dtproperties)
        End Sub
        '''<summary>
        '''There are no comments for tptest in the schema.
        '''</summary>
        Public Sub AddTotptest(ByVal tptest As tptest)
            MyBase.AddObject("tptest", tptest)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for EDM.dtproperties in the schema.
    '''</summary>
    '''<KeyProperties>
    '''id
    '''property
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="EDM", Name:="dtproperties"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class dtproperties
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new dtproperties object.
        '''</summary>
        '''<param name="id">Initial value of id.</param>
        '''<param name="property">Initial value of property.</param>
        '''<param name="version">Initial value of version.</param>
        Public Shared Function Createdtproperties(ByVal id As Integer, ByVal [property] As String, ByVal version As Integer) As dtproperties
            Dim dtproperties As dtproperties = New dtproperties
            dtproperties.id = id
            dtproperties.property = [property]
            dtproperties.version = version
            Return dtproperties
        End Function
        '''<summary>
        '''There are no comments for Property id in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property id() As Integer
            Get
                Return Me._id
            End Get
            Set
                Me.OnidChanging(value)
                Me.ReportPropertyChanging("id")
                Me._id = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("id")
                Me.OnidChanged
            End Set
        End Property
        Private _id As Integer
        Partial Private Sub OnidChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property objectid in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property objectid() As Global.System.Nullable(Of Integer)
            Get
                Return Me._objectid
            End Get
            Set
                Me.OnobjectidChanging(value)
                Me.ReportPropertyChanging("objectid")
                Me._objectid = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("objectid")
                Me.OnobjectidChanged
            End Set
        End Property
        Private _objectid As Global.System.Nullable(Of Integer)
        Partial Private Sub OnobjectidChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnobjectidChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property property in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [property]() As String
            Get
                Return Me._property
            End Get
            Set
                Me.OnpropertyChanging(value)
                Me.ReportPropertyChanging("property")
                Me._property = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
                Me.ReportPropertyChanged("property")
                Me.OnPropertyChanged("property")
            End Set
        End Property
        Private _property As String
        '''<summary>
        '''There are no comments for Property value in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property value() As String
            Get
                Return Me._value
            End Get
            Set
                Me.OnvalueChanging(value)
                Me.ReportPropertyChanging("value")
                Me._value = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("value")
                Me.OnvalueChanged
            End Set
        End Property
        Private _value As String
        Partial Private Sub OnvalueChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnvalueChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property uvalue in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property uvalue() As String
            Get
                Return Me._uvalue
            End Get
            Set
                Me.OnuvalueChanging(value)
                Me.ReportPropertyChanging("uvalue")
                Me._uvalue = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("uvalue")
                Me.OnuvalueChanged
            End Set
        End Property
        Private _uvalue As String
        Partial Private Sub OnuvalueChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnuvalueChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property lvalue in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property lvalue() As Byte()
            Get
                Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._lvalue)
            End Get
            Set
                Me.OnlvalueChanging(value)
                Me.ReportPropertyChanging("lvalue")
                Me._lvalue = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("lvalue")
                Me.OnlvalueChanged
            End Set
        End Property
        Private _lvalue() As Byte
        Partial Private Sub OnlvalueChanging(ByVal value() As Byte)
        End Sub
        Partial Private Sub OnlvalueChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property version in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property version() As Integer
            Get
                Return Me._version
            End Get
            Set
                Me.OnversionChanging(value)
                Me.ReportPropertyChanging("version")
                Me._version = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("version")
                Me.OnversionChanged
            End Set
        End Property
        Private _version As Integer
        Partial Private Sub OnversionChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnversionChanged()
        End Sub
    End Class
    '''<summary>
    '''There are no comments for EDM.tptest in the schema.
    '''</summary>
    '''<KeyProperties>
    '''log_time
    '''</KeyProperties>
    <Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="EDM", Name:="tptest"),  _
     Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
     Global.System.Serializable()>  _
    Partial Public Class tptest
        Inherits Global.System.Data.Objects.DataClasses.EntityObject
        '''<summary>
        '''Create a new tptest object.
        '''</summary>
        '''<param name="log_time">Initial value of log_time.</param>
        Public Shared Function Createtptest(ByVal log_time As Date) As tptest
            Dim tptest As tptest = New tptest
            tptest.log_time = log_time
            Return tptest
        End Function
        '''<summary>
        '''There are no comments for Property log_time in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property log_time() As Date
            Get
                Return Me._log_time
            End Get
            Set
                Me.Onlog_timeChanging(value)
                Me.ReportPropertyChanging("log_time")
                Me._log_time = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("log_time")
                Me.Onlog_timeChanged
            End Set
        End Property
        Private _log_time As Date
        Partial Private Sub Onlog_timeChanging(ByVal value As Date)
        End Sub
        Partial Private Sub Onlog_timeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property udp_tx in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property udp_tx() As Global.System.Nullable(Of Double)
            Get
                Return Me._udp_tx
            End Get
            Set
                Me.Onudp_txChanging(value)
                Me.ReportPropertyChanging("udp_tx")
                Me._udp_tx = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("udp_tx")
                Me.Onudp_txChanged
            End Set
        End Property
        Private _udp_tx As Global.System.Nullable(Of Double)
        Partial Private Sub Onudp_txChanging(ByVal value As Global.System.Nullable(Of Double))
        End Sub
        Partial Private Sub Onudp_txChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property udp_rx in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property udp_rx() As Global.System.Nullable(Of Double)
            Get
                Return Me._udp_rx
            End Get
            Set
                Me.Onudp_rxChanging(value)
                Me.ReportPropertyChanging("udp_rx")
                Me._udp_rx = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("udp_rx")
                Me.Onudp_rxChanged
            End Set
        End Property
        Private _udp_rx As Global.System.Nullable(Of Double)
        Partial Private Sub Onudp_rxChanging(ByVal value As Global.System.Nullable(Of Double))
        End Sub
        Partial Private Sub Onudp_rxChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property tcp_tx in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tcp_tx() As Global.System.Nullable(Of Double)
            Get
                Return Me._tcp_tx
            End Get
            Set
                Me.Ontcp_txChanging(value)
                Me.ReportPropertyChanging("tcp_tx")
                Me._tcp_tx = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("tcp_tx")
                Me.Ontcp_txChanged
            End Set
        End Property
        Private _tcp_tx As Global.System.Nullable(Of Double)
        Partial Private Sub Ontcp_txChanging(ByVal value As Global.System.Nullable(Of Double))
        End Sub
        Partial Private Sub Ontcp_txChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property tcp_rx in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property tcp_rx() As Global.System.Nullable(Of Double)
            Get
                Return Me._tcp_rx
            End Get
            Set
                Me.Ontcp_rxChanging(value)
                Me.ReportPropertyChanging("tcp_rx")
                Me._tcp_rx = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
                Me.ReportPropertyChanged("tcp_rx")
                Me.Ontcp_rxChanged
            End Set
        End Property
        Private _tcp_rx As Global.System.Nullable(Of Double)
        Partial Private Sub Ontcp_rxChanging(ByVal value As Global.System.Nullable(Of Double))
        End Sub
        Partial Private Sub Ontcp_rxChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property comment in the schema.
        '''</summary>
        <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
         Global.System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property comment() As String
            Get
                Return Me._comment
            End Get
            Set
                Me.OncommentChanging(value)
                Me.ReportPropertyChanging("comment")
                Me._comment = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true)
                Me.ReportPropertyChanged("comment")
                Me.OncommentChanged
            End Set
        End Property
        Private _comment As String
        Partial Private Sub OncommentChanging(ByVal value As String)
        End Sub
        Partial Private Sub OncommentChanged()
        End Sub
    End Class
End Namespace
