/****************************************************
  1)Ersätt NAMN1 med namnet på den tänkta classfil som
  skapas vid kompilering, t ex test1
  2)Spara sedan denna fil som test1.java och kör 
  kommandot 'javac <filnamn.java>' för att kompilera.
  Lycka till!
******************************************************/

class test{
  public static void main (String args[]) {
    System.out.println ("Hello World!");
  }
}
