'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
      If My.Application.SaveMySettingsOnExit Then
        My.Settings.Save()
      End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("sin(x)")> _
    Public Property Formula() As Global.System.String
      Get
        Return CType(Me("Formula"), Global.System.[String])
      End Get
      Set(value As Global.System.String)
        Me("Formula") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("-10")> _
    Public Property Xmin() As Global.System.String
      Get
        Return CType(Me("Xmin"), Global.System.[String])
      End Get
      Set(value As Global.System.String)
        Me("Xmin") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("10")> _
    Public Property Xmax() As Global.System.String
      Get
        Return CType(Me("Xmax"), Global.System.[String])
      End Get
      Set(value As Global.System.String)
        Me("Xmax") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("-5")> _
    Public Property Ymin() As Global.System.String
      Get
        Return CType(Me("Ymin"), Global.System.[String])
      End Get
      Set(value As Global.System.String)
        Me("Ymin") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("5")> _
    Public Property Ymax() As Global.System.String
      Get
        Return CType(Me("Ymax"), Global.System.[String])
      End Get
      Set(value As Global.System.String)
        Me("Ymax") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Property SaveFileName() As Global.System.String
      Get
        Return CType(Me("SaveFileName"), Global.System.[String])
      End Get
      Set(value As Global.System.String)
        Me("SaveFileName") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()> _
    Public Property SaveFileDirectory() As Global.System.String
      Get
        Return CType(Me("SaveFileDirectory"), Global.System.[String])
      End Get
      Set(value As Global.System.String)
        Me("SaveFileDirectory") = Value
      End Set
    End Property
        
    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("625, 481")> _
    Public Property WindowSize() As Global.System.Drawing.Size
      Get
        Return CType(Me("WindowSize"), Global.System.Drawing.Size)
      End Get
      Set(value As Global.System.Drawing.Size)
        Me("WindowSize") = Value
      End Set
    End Property
        
    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("100, 150")> _
    Public Property WindowPos() As Global.System.Drawing.Point
      Get
        Return CType(Me("WindowPos"), Global.System.Drawing.Point)
      End Get
      Set(value As Global.System.Drawing.Point)
        Me("WindowPos") = Value
      End Set
    End Property
        
    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property DrawDerivative() As Global.System.Boolean
      Get
        Return CType(Me("DrawDerivative"), Global.System.[Boolean])
      End Get
      Set(value As Global.System.Boolean)
        Me("DrawDerivative") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("False")> _
    Public Property DrawAntiderivative() As Global.System.Boolean
      Get
        Return CType(Me("DrawAntiderivative"), Global.System.[Boolean])
      End Get
      Set(value As Global.System.Boolean)
        Me("DrawAntiderivative") = value
      End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("True")> _
    Public Property ClearBeforeRedraw() As Global.System.Boolean
      Get
        Return CType(Me("ClearBeforeRedraw"), Global.System.[Boolean])
      End Get
      Set(value As Global.System.Boolean)
        Me("ClearBeforeRedraw") = Value
      End Set
    End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.GraphViewer.My.MySettings
            Get
                Return Global.GraphViewer.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
